// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJEMepzbAFP-kz7INQ_o4x7cDv1tncP0k',
    appId: '1:118047928754:web:5ebd820d76a391484e74ab',
    messagingSenderId: '118047928754',
    projectId: 'smt-phonesh-dev',
    authDomain: 'smt-phonesh-dev.firebaseapp.com',
    storageBucket: 'smt-phonesh-dev.appspot.com',
    measurementId: 'G-HNFVYS3WT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPApclFugTb2n609dtqWmY-rsKGcyJwTY',
    appId: '1:118047928754:android:c2658768aed2b4614e74ab',
    messagingSenderId: '118047928754',
    projectId: 'smt-phonesh-dev',
    storageBucket: 'smt-phonesh-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_vJC17clHAFVtV9FNXZj8BASCl6zPr_A',
    appId: '1:118047928754:ios:655b1ed1cc6811c54e74ab',
    messagingSenderId: '118047928754',
    projectId: 'smt-phonesh-dev',
    storageBucket: 'smt-phonesh-dev.appspot.com',
    iosBundleId: 'com.tech4mm.smtphonesh.smtPhoneshDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_vJC17clHAFVtV9FNXZj8BASCl6zPr_A',
    appId: '1:118047928754:ios:655b1ed1cc6811c54e74ab',
    messagingSenderId: '118047928754',
    projectId: 'smt-phonesh-dev',
    storageBucket: 'smt-phonesh-dev.appspot.com',
    iosBundleId: 'com.tech4mm.smtphonesh.smtPhoneshDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJEMepzbAFP-kz7INQ_o4x7cDv1tncP0k',
    appId: '1:118047928754:web:a1e37658f6111e8c4e74ab',
    messagingSenderId: '118047928754',
    projectId: 'smt-phonesh-dev',
    authDomain: 'smt-phonesh-dev.firebaseapp.com',
    storageBucket: 'smt-phonesh-dev.appspot.com',
    measurementId: 'G-KPSDNDZ281',
  );
}
